{{- if not .Values.ovhCredentials.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ovhcreds.secretName" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  region: {{ .Values.ovhCredentials.region | b64enc }}
  applicationKey: {{ .Values.ovhCredentials.applicationKey | b64enc }}
  applicationSecret: {{ .Values.ovhCredentials.applicationSecret | b64enc }}
  consumerKey: {{ .Values.ovhCredentials.consumerKey | b64enc }}
{{- end -}}
